defmodule RockSolid.SchemaStoreTest do
  use ExUnit.Case
  use ExUnitProperties

  alias RockSolid.Resolvers.RemoteResolver

  @moduletag timeout: 45_000
  @moduletag :integration

  setup_all do
    val = Application.fetch_env!(:rock_solid, :client_options)
    Application.put_env(:rock_solid, :client_options, [])

    on_exit(fn ->
      Application.put_env(:rock_solid, :client_options, val)
    end)

    :ok
  end

  # Generate correct schemas but don't validate because of mismatched `$ref` behaviour.
  # The schema has `$ref` + extra stuff but is in an older draft which ignores `$ref`
  @false_positives [
    "drupal-libraries.json",
    "yamllint.json",
    "staticwebapp.config.json",
    "catalog-info.json",
    "mineraft-recipe.json",
    "schema-org-thing.json"
  ]

  @impossible [
    # Wrong schemas
    ## Has "const": ["list", "of"] instead of "enum"
    "prometheus.json",
    ## Enums cannot match, idk what happened in that schema
    "stylelintrc.json",
    ## Duplicate empty {"type": "object"} in oneOf
    "schema-org-place.json",
    ## {oneOf: [{enum: []}, {enum: []}]}
    "jscsrc.json",
    # This is a YAML...
    "semgrep.json",
    # Has $ref to local file, unsupported yet
    "sarif-external-property-file-2.1.0-rtm.5.json",
    "sarif-external-property-file.json",
    # Unsupported regex features
    "pre-commit-config.json",
    "chisel-slices.json",
    # Broken remote ref
    "toolinfo.1.1.0.json",
    "sarif-external-property-file-2.1.0.json",
    # $dynamicRef
    "openapi-3.X.json",
    # Unknown local ref
    # to meta/core
    "openapi-arazzo-1.X.json",
    # osi-license
    "base-04.json",
    # osi-license
    "clasp.json",
    # contains a ref and no id, causing wrong resolution
    "databricks-asset-bundles.json",
    # {"type": "object", "enum": ["some_string"]}...
    # technically we can set it to false so that it passes, but better to warn the user
    "cloudify.json",
    # additionalProperties: false but also has an if/then/else statement with required
    # properties, meaning it can never match. The `additionalProperties` should be inside
    # the then/else clauses, not at the top
    "typo3.json",
    "minecraft-biome.json",
    "tunnelhub.json",
    # subschema has "type": "string" with "if": {"properties": ...} which always matches
    "minecraft-dimension.json",
    # Incorrect "$ref" to object + "type": "array" instead of having the "$ref"
    # as part of "items"
    "ti8m-cdk-environment-definition.json",
    # Contains oneOf [{type: string}, {type: string}]
    "jasonette.json",
    # {type: array, anyOf: [{type: object}, {type: object}]}
    "bamboo-spec.json"
  ]

  # Debug later
  @timeouts [
    # These ones cause Memory error!
    "renovate-inherited-schema-42.json",
    "renovate-global-schema-42.json",
    "renovate-40.json",
    "avro-avsc.json",
    "renovate-global-schema-41.json",
    "renovate-42.json",
    "renovate-41.json",
    "workflows.json",
    "abc-clinical-demand-forecast-1.0.0.json",
    "renovate-39.json",
    "cargo-make.json",
    "github-workflow.json",
    "lsdlschema.json",
    "specmatic.json",
    # Too large, don't even bother
    "kestra-0.18.0.json",
    "kestra-0.18.1.json",
    "kestra-0.18.2.json",
    "kestra-0.18.3.json",
    "kestra-0.19.0.json"
  ]

  # Schemas that at some point passed and should still pass
  @passing_schemas [
    "BizTalkServerApplicationSchema.json",
    "abc-inventory-module-data-1.0.0.json",
    "abc-inventory-module-data-2.0.0.json",
    "abc-inventory-module-data-3.0.0.json",
    "abc-inventory-module-data-4.0.0.json",
    "abc-inventory-module-data-5.1.0.json",
    "abc-inventory-module-data-5.2.0.json",
    "abc-supply-plan-1.0.0.json",
    "abc-supply-plan-2.0.0.json",
    "abc-supply-plan-3.0.0.json",
    "abc-supply-plan-4.0.0.json",
    "abc-supply-plan-5.0.0.json",
    "abc-supply-plan-6.0.0.json",
    "abc-supply-plan-7.0.0.json",
    "agripparc-1.2.json",
    "agripparc-1.3.json",
    "agripparc-1.4.json",
    "aiconfig-1.0.json",
    "aider-0.82.json",
    "aio-wasm-graph-config-1.0.0.json",
    "aio-wasm-graph-config-1.1.0.json",
    "aiproj-1.0.json",
    "aiproj-1.1.json",
    "aiproj-1.2.json",
    "aiproj-1.3.json",
    "aiproj-1.4.json",
    "aiproj-1.5.json",
    "aiproj-1.6.json",
    "aiproj-1.7.json",
    "aiproj-1.8.json",
    "aiproj-1.9.json",
    "airlock-microgateway-3.0.json",
    "airlock-microgateway-3.1.json",
    "airlock-microgateway-3.2.json",
    "aliases.json",
    "all-contributors.json",
    "amplify.json",
    "amx-muse.json",
    "any.json",
    "anywork-ac-1.0.json",
    "anywork-ac-1.1.json",
    "apibuilder.json",
    "apollo-router-2.8.1.json",
    "apollo-router-2.8.2.json",
    "apollo-router-2.9.0.json",
    "app-config.json",
    "apple-app-site-association.json",
    "appsettings.json",
    "appsscript.json",
    "appveyor.json",
    "architectfx.json",
    "artifacthub-repo.json",
    "asconfig-schema.json",
    "asmdef.json",
    "aspire-8.0.json",
    "assetlinks.json",
    "aurora-1.0.json",
    "aurora-1.1.json",
    "aurora-1.2.json",
    "aurora-1.3.json",
    "ava.json",
    "aws-cdk-appconfig-featureflags-1.0.0.json",
    "azure-containerapp-template.json",
    "azure-deviceupdate-import-manifest-4.0.json",
    "azure-deviceupdate-import-manifest-5.0.json",
    "azure-deviceupdate-manifest-definitions-4.0.json",
    "azure-deviceupdate-manifest-definitions-5.0.json",
    "azure-deviceupdate-update-manifest-4.json",
    "azure-devops-extension-manifest-1.0.json",
    "azure-iot-edge-deployment-1.0.json",
    "azure-iot-edge-deployment-2.0.json",
    "azure-iot-edge-deployment-template-1.0.json",
    "azure-iot-edge-deployment-template-2.0.json",
    "azure-iot-edge-deployment-template-3.0.json",
    "azure-iot-edge-deployment-template-4.0.json",
    "azure-iot-edgeagent-deployment-1.0.json",
    "azure-iot-edgeagent-deployment-1.1.json",
    "azure-iot-edgehub-deployment-1.0.json",
    "azure-iot-edgehub-deployment-1.1.json",
    "azure-iot-edgehub-deployment-1.2.json",
    "babelrc.json",
    "backportrc.json",
    "band-manifest.json",
    "base.json",
    "behat.json",
    "bettercodehub.json",
    "bigconfig.json",
    "bigquery-table.json",
    "bitrise-step.json",
    "bitrise.json",
    "bmml.json",
    "bootstraprc.json",
    "bosh-cpi-config.json",
    "bosh-deploy-config.json",
    "bower.json",
    "bowerrc.json",
    "boyka-config.json",
    "bozr.json",
    "bpkg.json",
    "browser.i18n.json",
    "buf.gen.json",
    "buf.json",
    "buf.lock.json",
    "buf.plugin.json",
    "buf.policy.json",
    "buf.work.json",
    "bukkit-plugin.json",
    "bun-lock.json",
    "bunfig.json",
    "bungee-plugin.json",
    "bxci.schema-1.0.1.json",
    "bxci.schema-1.0.json",
    "bxci.schema-2.0.0.json",
    "bxci.schema-2.x.json",
    "cargo-lints-cargo.json",
    "cargo-lints-clippy.json",
    "cargo-lints-rust.json",
    "cargo-lints-rustdoc.json",
    "cargo-mutants-config.json",
    "cargo.json",
    "case_schema.json",
    "cdk.json",
    "changepacks.json",
    "chart-lock.json",
    "chart.json",
    "cheatsheets.json",
    "chrome-extension-locales-messages.json",
    "chutzpah.json",
    "cibuildwheel.json",
    "cinnamon-spice-metadata.json",
    "cinnamon-spice-settings.json",
    "cinnamon-spice.info.json",
    "clang-format-18.x.json",
    "clang-format-21.x.json",
    "clang-tidy.json",
    "clangd.json",
    "claude-code-keybindings.json",
    "clib.json",
    "cloud-sdk-pipeline-config-schema.json",
    "cloudbuild.json",
    "cloudfoundry-application-manifest.json",
    "codeclimate.json",
    "codecov.json",
    "codeship-services.json",
    "coffeelint.json",
    "commands.json",
    "commitlintrc.json",
    "compile-commands.json",
    "compilerdefaults.json",
    "component-detection-manifest.json",
    "component.json",
    "container-structure-test.json",
    "content-security-policy-report-2.json",
    "contextive-glossary.json",
    "cosmos-config.json",
    "creatomic.json",
    "crowdin.json",
    "cryproj.52.schema.json",
    "cryproj.53.schema.json",
    "cryproj.54.schema.json",
    "cryproj.55.schema.json",
    "cryproj.dev.schema.json",
    "cryproj.json",
    "csscomb.json",
    "csslintrc.json",
    "ctfd.json",
    "dart-build.json",
    "dart-test.json",
    "debugsettings.json",
    "dependabot-2.0.json",
    "dependabot.json",
    "deployed.json",
    "detekt-1.14.1.json",
    "detekt-1.22.0.json",
    "devinit.schema-1.0.json",
    "devinit.schema-2.0.json",
    "devinit.schema-3.0.json",
    "devinit.schema-4.0.json",
    "devinit.schema-5.0.json",
    "devinit.schema-6.0.json",
    "devup.json",
    "djlint.json",
    "docfx.json",
    "docker-bake.json",
    "docker-extension-metadata.json",
    "dockerd.json",
    "docs-mcp-manifest.json",
    "dotnet-releases-index.json",
    "dotnet-tools.json",
    "dotnetcli.host.json",
    "drupal-breakpoints.json",
    "drupal-config.json",
    "drupal-info.json",
    "drupal-layouts.json",
    "drupal-links-action.json",
    "drupal-links-contextual.json",
    "drupal-links-menu.json",
    "drupal-links-task.json",
    "drupal-migration.json",
    "drupal-permissions.json",
    "drupal-recipe.json",
    "drupal-routing.json",
    "drupal-services.json",
    "drush.site.yml.json",
    "dtool-dataset-metadata-1.0.json",
    "easyvcr-net.json",
    "electron-builder.json",
    "elgato-stream-deck-plugin.json",
    "elm.json",
    "embrace-config-schema-1.0.0.json",
    "epr-manifest.json",
    "es6importsorterrc.json",
    "eslintrc.json",
    "esmrc.json",
    "esquio.json",
    "ethereum-erc1155.json",
    "ethereum-erc721.json",
    "evolving-resolutive-process-notation-1.0.json",
    "expo-37.0.0.json",
    "expo-38.0.0.json",
    "expo-39.0.0.json",
    "expo-40.0.0.json",
    "expo-41.0.0.json",
    "expo-42.0.0.json",
    "expo-46.0.0.json",
    "expo-50.0.0.json",
    "expo-52.0.0.json",
    "expo-53.0.0.json",
    "fabric.mod.json",
    "factorial-drupal-breakpoints-css-0.2.0.json",
    "feed-1.json",
    "feed.json",
    "first-timers.json",
    "fly.json",
    "foundryvtt-base-package-manifest.json",
    "foundryvtt-template.json",
    "foxx-manifest.json",
    "gadget-yaml.json",
    "gcp-blueprint-metadata.json",
    "gematik-test-hcpis.json",
    "gematik-test-hcps.json",
    "gematik-test-insurances.json",
    "gematik-test-patients.json",
    "gematik-tiger.json",
    "geojson.json",
    "gitea-issue-config.json",
    "gitea-issue-forms.json",
    "github-action.json",
    "github-discussion.json",
    "github-funding.json",
    "github-issue-config.json",
    "github-issue-forms.json",
    "github-release-config.json",
    "github-workflow-template-properties.json",
    "gitversion.json",
    "global.json",
    "gpc.json",
    "grafana-dashboard-5.x.json",
    "grunt-clean-task.json",
    "grunt-copy-task.json",
    "grunt-cssmin-task.json",
    "grunt-jshint-task.json",
    "grunt-task.json",
    "hammerkit.json",
    "haxelib.json",
    "helmfile.json",
    "hemtt-0.6.2.json",
    "host-meta.json",
    "host.json",
    "htmlhint.json",
    "httpmockrc.json",
    "hugo-theme.json",
    "hugo.json",
    "huskyrc.json",
    "hws-config.json",
    "ide.host.json",
    "imageoptimizer.json",
    "img-catapult-psp-1.0.0.json",
    "imgbotconfig.json",
    "importmap.json",
    "install.json",
    "jasmine.json",
    "jdt.json",
    "jekyll.json",
    "jest.json",
    "jovo-language-model.json",
    "jreleaser-1.10.0.json",
    "jreleaser-1.11.0.json",
    "jreleaser-1.12.0.json",
    "jreleaser-1.13.0.json",
    "jreleaser-1.13.1.json",
    "jreleaser-1.14.0.json",
    "jreleaser-1.15.0.json",
    "jreleaser-1.16.0.json",
    "jreleaser-1.17.0.json",
    "jreleaser-1.18.0.json",
    "jreleaser-1.19.0.json",
    "jreleaser-1.20.0.json",
    "jreleaser-1.21.0.json",
    "jreleaser-1.22.0.json",
    "jreleaser-1.23.0.json",
    "jreleaser-1.24.0.json",
    "jreleaser-1.6.0.json",
    "jreleaser-1.7.0.json",
    "jreleaser-1.8.0.json",
    "jreleaser-1.9.0.json",
    "jsbeautifyrc-nested.json",
    "jsbeautifyrc.json",
    "jsconfig.json",
    "jscpd.json",
    "jsdoc-1.0.0.json",
    "jshintrc.json",
    "jsinspectrc.json",
    "json-api-1.0.json",
    "json-patch.json",
    "knowledge-unit.json",
    "kode-ci-build-1.0.0.json",
    "kong_json_schema.json",
    "ksp-avc.json",
    "ksp-ckan.json",
    "kubernetes-definitions.json",
    "kustomization.json",
    "label-commenter-config.json",
    "language-configuration.json",
    "launchsettings.json",
    "lazydocker.json",
    "lefthook.json",
    "lego.json",
    "lerna.json",
    "lgtm.json",
    "libman.json",
    "license-report-config.json",
    "licenses.1.json",
    "linkinator-config.json",
    "lintstagedrc.schema.json",
    "linutil-tab-data.json",
    "linutil-tabs.json",
    "liquibase-3.2.json",
    "liquibase.json",
    "local.settings.json",
    "loki.json",
    "loobin-1.0.json",
    "lsdlschema-0.7.json",
    "lsdlschema-1.0.json",
    "lsdlschema-1.2.json",
    "lsdlschema-2.0.json",
    "lsdlschema-3.0.json",
    "lsdlschema-3.1.json",
    "lsdlschema-3.2.json",
    "lsdlschema-3.3.json",
    "luaurc.json",
    "maestro-flow.json",
    "mail-servers-config.json",
    "markdown-link-check.json",
    "maturin.json",
    "mboats-config-0.1.json",
    "mboats-config-0.2.json",
    "mdxlintrc.json",
    "micro-syntax.json",
    "micro.json",
    "mimetypes.json",
    "minecraft-advancement.json",
    "minecraft-configured-carver.json",
    "minecraft-custom-main-menu-mod.json",
    "minecraft-damage-type.json",
    "minecraft-dimension-type.json",
    "minecraft-lang.json",
    "minecraft-pack-mcmeta.json",
    "minecraft-particle.json",
    "minecraft-tag.json",
    "minecraft-template-pool.json",
    "minecraft-texture-mcmeta.json",
    "minecraft-trim-material.json",
    "minecraft-trim-pattern.json",
    "mkdocs-1.0.json",
    "mkdocs-1.6.json",
    "mocharc.json",
    "modernizrrc.json",
    "monade-stack-config.json",
    "monika-config-schema.json",
    "mprocs-0.6.4.json",
    "mta.json",
    "mtad.json",
    "mtaext.json",
    "mycode.json",
    "nest-cli.json",
    "netlify.json",
    "nightwatch.json",
    "ninjs-1.0.json",
    "ninjs-1.1.json",
    "ninjs-1.2.json",
    "ninjs-1.3.json",
    "ninjs-1.4.json",
    "nodehawkrc.json",
    "nodemon.json",
    "now.json",
    "npm-badges.json",
    "npm-link-up.json",
    "npmpackagejsonlintrc.json",
    "nswag.json",
    "nuejs-site.json",
    "nuget-project-3.3.0.json",
    "nuget-project.json",
    "nycrc.json",
    "ocelot.json",
    "ogen.json",
    "okh.json",
    "omletrc.json",
    "omnisharp.json",
    "one-changelog-schema-0.1.json",
    "one-service-descriptor-schema-0.1.json",
    "openfin.json",
    "opensrm.json",
    "openutau-character.json",
    "openutau-ustx.json",
    "openweather.current.json",
    "openweather.roadrisk.json",
    "package.manifest-7.0.0.json",
    "package.manifest-8.0.0.json",
    "package.manifest.json",
    "pactspec.json",
    "pantsbuild-2.14.0.json",
    "pantsbuild-2.15.0.json",
    "pantsbuild-2.16.0.json",
    "pantsbuild-2.17.0.json",
    "pantsbuild-2.18.0.json",
    "pantsbuild-2.19.0.json",
    "pantsbuild-2.20.0.json",
    "pantsbuild-2.21.0.json",
    "pantsbuild-2.24.0.json",
    "pantsbuild-2.26.0.json",
    "pantsbuild-2.30.0.json",
    "pantsbuild-2.31.0.json",
    "partial-black.json",
    "partial-cibuildwheel.json",
    "partial-dfc.json",
    "partial-eslint-plugins.json",
    "partial-fastapi.json",
    "partial-fusion-pack-metadata.json",
    "partial-fusion-texture-metadata.json",
    "partial-mypy.json",
    "partial-pdm-dockerize.json",
    "partial-pdm.json",
    "partial-pixi.json",
    "partial-poetry.json",
    "partial-pyright.json",
    "partial-pytest.json",
    "partial-repo-review.json",
    "partial-scikit-build.json",
    "partial-setuptools-scm.json",
    "partial-setuptools.json",
    "partial-taskipy.json",
    "pattern.json",
    "pdm.json",
    "pep-723.json",
    "petstore-v1.0.json",
    "pgap_yaml_input_reader.json",
    "phrase.json",
    "phraseapp.json",
    "plagiarize-0.0.json",
    "plagiarize-me-0.0.json",
    "plagiarize-me.json",
    "plagiarize.json",
    "pm2-ecosystem.json",
    "pnpm-workspace.json",
    "pocketmine-plugin.json",
    "popxf-corr-1.0.json",
    "postcssrc.json",
    "powerpages-web-template-manifest.json",
    "powerpages.config.json",
    "pre-commit-hooks.json",
    "prek.json",
    "prettierrc-1.8.2.json",
    "prettierrc-2.8.8.json",
    "prettierrc.json",
    "prisma.json",
    "problem-object-rfc9457.json",
    "project-1.0.0-beta3.json",
    "project-1.0.0-beta4.json",
    "project-1.0.0-beta5.json",
    "project-1.0.0-beta6.json",
    "project-1.0.0-beta8.json",
    "project-1.0.0-rc1.json",
    "project-1.0.0-rc2.json",
    "project.json",
    "projektor.json",
    "prometheus-alertmanager.json",
    "prometheus.rules.json",
    "prometheus.rules.test.json",
    "proxies.json",
    "pterodactyl.json",
    "publiccode.json",
    "pubspec.json",
    "pull-request-labeler.json",
    "putout.json",
    "pylock.json",
    "qfconfig.json",
    "qodana-1.0.json",
    "qwen-code-settings.json",
    "radiohound-v0.json",
    "rc3-auth-0.0.3.json",
    "rc3-collection-0.0.3.json",
    "rc3-environment-0.0.3.json",
    "rc3-folder-0.0.3.json",
    "rc3-request-0.0.3.json",
    "rc3-settings-0.0.3.json",
    "rehyperc.json",
    "remarkrc.json",
    "replit.json",
    "revola.json",
    "roomodes.json",
    "rudder-techniques.json",
    "ruff.json",
    "rumdl.json",
    "rust-project.json",
    "rust-toolchain.json",
    "rustfmt.json",
    "ryl.json",
    "safebox-schema-v1.0.0.json",
    "sake.json",
    "samt.json",
    "samtrc.json",
    "scarb.json",
    "schema-catalog.json",
    "semantic-release.json",
    "sergen.json",
    "servicehub.config.schema.json",
    "servicehub.service.schema.json",
    "settings.job.json",
    "sigrid-scope-file.schema.json",
    "sil-kit-participant-configuration.json",
    "sil-kit-registry-configuration.json",
    "size-limit.json",
    "skypilot-task.json",
    "slack-app-manifest.json",
    "snowflake-config.json",
    "snowflake-connections.json",
    "solidaritySchema.json",
    "solution-filter.json",
    "sourcehut-build-0.41.2.json",
    "sourcehut-build-0.65.0.json",
    "sourcemap-v3.json",
    "sourcery_yaml_schema.json",
    "specif-1.0.json",
    "specif-1.1.json",
    "sponge-mixins.json",
    "sprite.json",
    "sqlc-2.0.json",
    "stackblitzrc.json",
    "stale.json",
    "streamlit-config.json",
    "stylintrc.json",
    "stylua.json",
    "sublime-syntax.json",
    "swa-cli.config.json",
    "taplo.json",
    "task.json",
    "taskfile.json",
    "taurus.json",
    "templatesources.json",
    "tldr.json",
    "tmuxinator.json",
    "tombi.json",
    "tox.json",
    "traefik-v2-file-provider.json",
    "traefik-v2.json",
    "traefik-v3-file-provider.json",
    "traefik-v3.json",
    "travis.json",
    "treefmt.json",
    "truescript.json",
    "ts-force-config.json",
    "tsconfig.json",
    "tsd.json",
    "tsdrc.json",
    "tsoa.json",
    "twee-ts.config.json",
    "ty.json",
    "typewiz.json",
    "typings.json",
    "typingsrc.json",
    "unist.json",
    "up.json",
    "uplugin.json",
    "uproject.json",
    "uv.json",
    "venvplus-schema-v1.0.0.json",
    "vespertide-migration.json",
    "vespertide-model.json",
    "vespertide.json",
    "vhwdebugger-binding-schema.json",
    "vs-nesting.json",
    "vsconfig.json",
    "vsext.json",
    "vsix-manifestinjection.json",
    "vsix-publish.json",
    "vsls.json",
    "vss-extension.json",
    "vtcfg-v19.0.0.json",
    "vtesttree-schema-v1.0.0.json",
    "vtesttree-schema-v2.0.0.json",
    "vtesttree-schema-v2.1.0.json",
    "vtesttree-schema-v2.2.0.json",
    "vtesttree-schema-v2.3.0.json",
    "vtesttree-schema-v2.4.0.json",
    "warp-keysets.json",
    "warp-themes.json",
    "warp-workflows.json",
    "web-manifest-app-info.json",
    "web-manifest-combined.json",
    "web-manifest-share-target.json",
    "web-manifest.json",
    "webextension.json",
    "webjob-publish-settings.json",
    "webjobs-list.json",
    "winget-pkgs-installer-1.0.0.json",
    "winget-pkgs-singleton-0.1.json",
    "winutil-applications.json",
    "winutil-presets.json",
    "xs-app.json",
    "xunit-2.2.json",
    "xunit-2.3.json",
    "xunit.runner.schema.json",
    "yamlfmt.json",
    "zarf.json",
    "grunt-watch-task.json",
    "bxci.schema-3.x.json",
    "azure-deviceupdate-update-manifest-5.json",
    "drone.json",
    "ubuntu-server-autoinstall.json",
    "starlake.json",
    "pull-request-labeler-5.json",
    "declarative-automation-bundles.json",
    "rancher-fleet-0.5.json",
    "youtrack-app.json",
    "jsonld.json",
    "vim-addon-info.json",
    "winget-pkgs-locale-1.0.0.json",
    "winget-pkgs-singleton-1.0.0.json",
    "rancher-fleet-0.8.json",
    "chrome-manifest.json",
    "grpc-api-gateway.json",
    "lazygit.json",
    "markdownlint.json",
    "dss-2.0.0.json",
    "sarif-1.0.0.json",
    "tmlanguage.json",
    # Modified to pass, original was likely auto generated and the
    # schema doesn't make sense or is incomplete. The modified schemas
    # are still equivalent or a stricter version of the originals
    "uxp-manifest-5.json",
    "minecraft-loot-table.json",
    "pyrseas-0.8.json",
    "datalogic-scan2deploy-ce.json",
    "datalogic-scan2deploy-android.json",
    "gaspar-1.0.json",
    "gaspar-3.0.json",
    "hatch.json",
    "block.json",
    "packer.json",
    "cloud-run-v1.json",
    "glazewm.json",
    "codeship-steps.json",
    "golangci-lint.json",
    "jfrog-pipelines.json",
    "map-file.v1.json"
  ]

  describe "regression schemas" do
    @describetag regression: false
    for filename <- @passing_schemas do
      test "schema #{filename}" do
        Path.join(["test", "support", "schemastore", unquote(filename)])
        |> File.read!()
        |> JSON.decode!()
        |> check_schema()
      end
    end
  end

  describe "failing schemas" do
    @describetag regression: true

    for filename <- File.ls!(Path.join(["test", "support", "schemastore"])),
        filename not in (@passing_schemas ++ @false_positives ++ @timeouts ++ @impossible) do
      test "schema #{filename}" do
        Path.join(["test", "support", "schemastore", unquote(filename)])
        |> File.read!()
        |> JSON.decode!()
        |> check_schema()
      end
    end
  end

  def check_schema(schema) do
    schema = RockSolid.Migration.migrate(schema, {RemoteResolver, []})
    root = JSV.build!(schema, resolver: [RockSolid.Resolver])

    check all generated <- RockSolid.from_schema(schema), max_runs: 20 do
      assert {:ok, _} = JSV.validate(generated, root)
    end
  end
end
